version: 0.0
os: windows
files:
  - source: /
    destination: C:\TestingPipeline\apidocker

hooks:
  BeforeInstall:
    - location: scripts\before_install.bat
  AfterInstall:
    - location: scripts\after_install.bat
  ApplicationStart:
    - location: scripts\application_start.bat
